### ISSUE TITLE
Floating Point Error With Daily Commands

### ISSUE THREAD

**Issue by jakk-danger** [entersudonym/freedom-bot#1]
![image](https://user-images.githubusercontent.com/65435393/82110230-3be22480-96d8-11ea-93a3-1c96f4abd4c1.png)

**Comment by jakk-danger** [comment]
Is it fixed yet?

**Comment by entersudonym** [comment]
no

**Comment by jakk-danger** [comment]
WTF!!!

**Comment by entersudonym** [comment]
This is testing the GitHub webhook.
